language: java
jdk:
  - oraclejdk8

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - sudo apt-get update -qq
  - sudo apt-get install -qq zookeeper zookeeperd

notifications:
  email:
    on_failure: change
    on_success: never
